import type { MetadataRoute } from "next";

// /robots.txt — auto-generated by Next.js. Tells crawlers which pages they
// can index. Points search engines at our sitemap.
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: ["/api/"], // Keep API routes private — they're not pages.
      },
    ],
    sitemap: "https://fridgebee.app/sitemap.xml",
    host: "https://fridgebee.app",
  };
}
