import type { MetadataRoute } from "next";

// Sitemap — auto-generated by Next.js at /sitemap.xml. Lists all public pages
// for Google Search Console + other search engine crawlers. Edit this file
// when you add new public routes (e.g. new blog posts).
const BASE = "https://fridgebee.app";

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date();
  return [
    { url: `${BASE}/welcome`,  lastModified: now, changeFrequency: "weekly",  priority: 1.0 },
    { url: `${BASE}/`,         lastModified: now, changeFrequency: "weekly",  priority: 0.9 },
    { url: `${BASE}/blog`,     lastModified: now, changeFrequency: "weekly",  priority: 0.8 },
    { url: `${BASE}/blog/paneer-onion-tomato`, lastModified: now, changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE}/contact`,  lastModified: now, changeFrequency: "yearly",  priority: 0.5 },
    { url: `${BASE}/privacy`,  lastModified: now, changeFrequency: "yearly",  priority: 0.4 },
  ];
}
